In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style('darkgrid')

In [86]:
def oracle(df, opt):
    # Drop unused columns
    df = df.drop(['runtimesd', 'energysd'], axis=1)

    df['opt'] = df.apply(lambda row: opt[row['size']], axis=1)

    # todo

In [116]:
def mean(df):
    # Drop unused columns
    df = df.drop(['runtimesd', 'energysd'], axis=1)

    # Normalise runtime and energy consumption
    mt = df[df['threads'] == 'mt']
    df['runtime'] = df.apply(lambda row: 100 - mt[mt['size'] == row['size']]['runtime'].iloc[0] / row['runtime'] * 100, axis=1)
    df['energy']  = df.apply(lambda row: 100 - mt[mt['size'] == row['size']]['energy'].iloc[0] / row['energy'] * 100, axis=1)

    # Drop unused columns and rows
    df = df.drop('size', axis=1)
    df = df[df['threads'] != 'mt']

    # Mean per thread-count
    return df.groupby('threads').mean(numeric_only=True).round(0).astype(int)

In [121]:
#df = pd.read_csv('data/compare_rust.csv')
#oracle(df, { 500: 16, 1000: 16, 1500: 1 })
#mean(df)

In [122]:
df = pd.read_csv('data/compare_matmul.csv')
oracle(df, { 500: 16, 1000: 16, 1500: 1 })
mean(df)

         runtime  energy
threads
12            25       7
16            14       4
8             48      19

In [118]:
df = pd.read_csv('data/compare_nbody.csv')
oracle(df, { 10000: 16, 25000: 16, 40000: 16 })
mean(df)

EmptyDataError: No columns to parse from file

In [119]:
df = pd.read_csv('data/compare_relax.csv')
oracle(df, { 10000: 16, 25000: 14, 40000: 12 })
mean(df)

         runtime  energy
threads
12            -4      -6
16           -10       3
8             31      10